# Generated by Django 2.0.3 on 2018-03-31 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aureas_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listmodel',
            name='choice',
            field=models.CharField(max_length=1),
        ),
    ]
