# Generated by Django 2.0.3 on 2018-03-31 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Aureas_App', '0003_auto_20180331_1444'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listmodel',
            options={'ordering': ['-choice', '-upload']},
        ),
    ]
