# Generated by Django 2.0.3 on 2018-03-31 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aureas_App', '0004_auto_20180331_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listmodel',
            name='upload',
            field=models.FilePathField(path='static/', recursive=True),
        ),
    ]
