# Generated by Django 2.0.3 on 2018-03-31 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aureas_App', '0005_auto_20180331_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listmodel',
            name='upload',
            field=models.FilePathField(allow_folders=True, path='static/', recursive=True),
        ),
    ]
