# Generated by Django 2.0.3 on 2018-03-31 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aureas_App', '0006_auto_20180331_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listmodel',
            name='upload',
            field=models.FilePathField(match='.*\\.(mp3|wav)$', path='Aureas_App/static/', recursive=True),
        ),
    ]
