# Generated by Django 2.0.3 on 2018-03-31 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aureas_App', '0007_auto_20180331_1518'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listmodel',
            options={'ordering': ['-upload']},
        ),
        migrations.RemoveField(
            model_name='listmodel',
            name='choice',
        ),
        migrations.AlterField(
            model_name='listmodel',
            name='upload',
            field=models.FilePathField(match='.*\\.(mp3|wav)$', recursive=True),
        ),
    ]
